### ISSUE TITLE
Fatal error: Class undefined: V8Js

### ISSUE THREAD

**Issue by Snaver** [phpv8/heroku-v8js#1]
Hi

I can't for the life of me get this to work, it appears that V8Js isn't loaded. I assume this should be automagically available in my script? I wonder if I've missed a step?

My setup:

- Normal heroku setup
- Ran 'heroku config:set HEROKU_PHP_PLATFORM_REPOSITORIES="https://heroku-v8js.s3.amazonaws.com/dist-cedar-14-stable/packages.json"'
- Procfile 'web: vendor/bin/heroku-hhvm-apache2'
- index.php with V8Js invoking code

Any hints for what I might have missed would be a great help!

**Comment by stesie** [comment]
V8Js is a *PHP* extension, it does *not* apply to HHVM

**Comment by Snaver** [comment]
Ah yes, sorry that was me testing.. 

My actual Procfile: web: vendor/bin/heroku-php-apache2

**Comment by dzuelke** [comment]
You also need to require `ext-v8js` in your composer.json.

**Comment by Snaver** [comment]
Thank you dzuelke, this was the step I was missing :) 

Much appreciated !
